secretProviderClass:
  name: vault-prod
  roleName: prod
  secretName: prod
  objects:
    - objectName: "wit-ai-token"
      secretPath: "secret/prod"
      secretKey: "wit-ai-token"
    - objectName: "kafka-ui-user"
      secretPath: "secret/prod"
      secretKey: "kafka-ui-user"
    - objectName: "kafka-ui-password"
      secretPath: "secret/prod"
      secretKey: "kafka-ui-password"
    - objectName: "internal-key-header"
      secretPath: "secret/prod"
      secretKey: "internal-key-header"
    - objectName: "jwt-access-key"
      secretPath: "secret/prod"
      secretKey: "jwt-access-key"
    - objectName: "jwt-refresh-key"
      secretPath: "secret/prod"
      secretKey: "jwt-refresh-key"
    - objectName: "orchestrator-db-password"
      secretPath: "secret/prod"
      secretKey: "orchestrator-db-password"
    - objectName: "orchestrator-db-port"
      secretPath: "secret/prod"
      secretKey: "orchestrator-db-port"
    - objectName: "orchestrator-db-user"
      secretPath: "secret/prod"
      secretKey: "orchestrator-db-user"
    - objectName: "telegram-bot-db-password"
      secretPath: "secret/prod"
      secretKey: "telegram-bot-db-password"
    - objectName: "telegram-bot-db-user"
      secretPath: "secret/prod"
      secretKey: "telegram-bot-db-user"
    - objectName: "telegram-bot-token"
      secretPath: "secret/prod"
      secretKey: "telegram-bot-token"
    - objectName: "docker-config-json"
      secretPath: "secret/default"
      secretKey: "docker-config-json"
    - objectName: "deepseek-auth-token"
      secretPath: "secret/prod"
      secretKey: "deepseek-auth-token"
    - objectName: "payment-db-user"
      secretPath: "secret/prod"
      secretKey: "payment-db-user"
    - objectName: "payment-db-password"
      secretPath: "secret/prod"
      secretKey: "payment-db-password"
    - objectName: "qa-robokassa-login-shop-id"
      secretPath: "secret/prod"
      secretKey: "qa-robokassa-login-shop-id"
    - objectName: "qa-robokassa-password-one"
      secretPath: "secret/prod"
      secretKey: "qa-robokassa-password-one"
    - objectName: "qa-robokassa-password-two"
      secretPath: "secret/prod"
      secretKey: "qa-robokassa-password-two"
    - objectName: "qa-robokassa-test-password-one"
      secretPath: "secret/prod"
      secretKey: "qa-robokassa-test-password-one"
    - objectName: "qa-robokassa-test-password-two"
      secretPath: "secret/prod"
      secretKey: "qa-robokassa-test-password-two"