server:
  port: 8084


orchestrator:
  host: overridetech.ru

integration:
  internal:
    host:
      orchestrator: http://localhost:8081
      recognizer: http://localhost:8080

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        hbm2ddl:
          auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml


  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:5436}/payments-db
    username: ${PAYMENT_DB_USER:postgres}
    password: ${PAYMENT_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver




logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.kafka: INFO

robokassa:
  login-shop-id: ${ROBOKASSA_LOGIN_SHOP_ID}
  password-one: ${ROBOKASSA_PASSWORD_ONE}
  password-two: ${ROBOKASSA_PASSWORD_TWO}
  test-password-one: ${ROBOKASSA_TEST_PASSWORD_ONE}
  test-password-two: ${ROBOKASSA_TEST_PASSWORD_TWO}
  subscription-amount: 1
  base-url: https://auth.robokassa.ru